# Generated by Django 4.2.5 on 2024-05-07 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0003_remove_uploadeddocument_key_userfiledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='access_level',
            field=models.CharField(choices=[('delete', 'Delete'), ('edit', 'Edit'), ('download', 'Download')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='shared_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='shared_with_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents', to='auth.group'),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='shared_with_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
