# Generated by Django 4.2.5 on 2024-05-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='Role',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='managers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
